exports.wineCellarHardware = [
  {
    name: "12 Inch Round Ladder Pull",
    slug: "12-inch-round-ladder-pull",
    image: "images/wineCellarHardwares/LP8X8.png",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "12 Inch Square Ladder Pull",
    slug: "12-inch-square-ladder-pull",
    image: "images/wineCellarHardwares/SLP12x12.jpg",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "18 Inch Square Pull",
    slug: "18-inch-square-pull",
    image: "images/wineCellarHardwares/SQ18x18.png",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "24 Inch Ladder Pull",
    slug: "24-inch-ladder-pull",
    image: "images/wineCellarHardwares/LP24x24.png",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "36 Inch Ladder Pull",
    slug: "36-inch-ladder-pull",
    image: "images/wineCellarHardwares/LP36x36.jpg",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Standard Pivot Hinge",
    slug: "standard-pivot-hinge",
    image: "images/wineCellarHardwares/SRPPH01.png",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Hydraulic Pivot Hinges",
    slug: "hydraulic-pivot-hinges",
    image: "images/wineCellarHardwares/CRL380.jpeg",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "HVY Pivot Bevel",
    image: "images/wineCellarHardwares/SRPPH01.png",
    slug: "hvy-pivot-bevel",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Lock",
    slug: "lock",
    image: "images/wineCellarHardwares/Glass-Door-Lock-300x204.png",
    hardware_category_slug: "door-locks",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "U-Channel (1/2)",
    image: "images/wineCellarHardwares/u-channel-1-2.jpg",
    slug: "u-channel-1-2",
    hardware_category_slug: "mounting-channels",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "U-Channel (3/8)",
    image: "images/wineCellarHardwares/u-channel-3-8.jpg",
    slug: "u-channel-3-8",
    hardware_category_slug: "mounting-channels",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
];
