exports.wineCellarFinishes = [
    {
        name: "Brushed Bronze",
        slug: "brushed-bronze",
        image: "images/wineCellarFinishes/brushed_bronze.jpg",
        partNumber: "wine-cellar-finish-brushed-bronze",
        cost: 0,
        status: true,
    },
    {
        name: "Polished Nickel",
        slug: "polished-nickel",
        image: "images/wineCellarFinishes/polished_nickle.jpg",
        partNumber: "wine-cellar-finish-polished-nickel",
        cost: 0,
        status: true,
    },
    {
        name: "Satin Brass",
        slug: "satin-brass",
        image: "images/wineCellarFinishes/satin_brass.jpg",
        partNumber: "wine-cellar-finish-satin-brass",
        cost: 0,
        status: true,
    },
    {
        name: "Matte Black",
        slug: "matte-black",
        image: "images/wineCellarFinishes/matte_black.jpg",
        partNumber: "wine-cellar-finish-matte-black",
        cost: 0,
        status: true,
    },
    {
        name: "Oil Rubbed Bronze",
        slug: "oil-rubbed-bronze",
        image: "images/wineCellarFinishes/oil_rubbed_bronze.jpg",
        partNumber: "wine-cellar-finish-oil-rubbed-bronze",
        cost: 0,
        status: true,
    },
    {
        name: "Brushed Nickel",
        slug: "brushed-nickel",
        image: "images/wineCellarFinishes/brushed_nickle.jpg",
        partNumber: "wine-cellar-finish-brushed-nickel",
        cost: 0,
        status: true,
    },
    {
        name: "Polished Chrome",
        slug: "polished-chrome",
        image: "images/wineCellarFinishes/polished_chrome.jpg",
        partNumber: "wine-cellar-finish-polished-chrome",
        cost: 0,
        status: true,
    },
];
